---
name: Security
on:
  push:
    branches:
      - main
      - release/*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
  schedule:
    # run every day
    - cron: "0 1 * * *"

jobs:
  # https://github.com/github/codeql-action
  codeql:
    name: CodeQL Analysis
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: percona-platform/checkout@v2.3.1

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - name: Check out correct tree
        if: ${{ github.event_name == 'pull_request' }}
        run: git checkout HEAD^2

      - name: Initialize CodeQL tools
        uses: percona-platform/codeql-action/init@v1
        with:
          config-file: ./.github/codeql.yml

      - name: Perform CodeQL analysis
        uses: percona-platform/codeql-action/analyze@v1

  # https://github.com/github/ossar-action
  ossar:
    name: OSSAR Analysis
    timeout-minutes: 5

    strategy:
      matrix:
        os: [windows-latest] # replace with ubuntu-latest once it is supported

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: percona-platform/checkout@v2.3.1

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - name: Check out correct tree
        if: ${{ github.event_name == 'pull_request' }}
        run: git checkout HEAD^2

      - name: Install .NET
        uses: percona-platform/setup-dotnet@v1
        with:
          dotnet-version: "3.1.201"

      - name: Perform OSSAR analysis
        uses: percona-platform/ossar-action@v1
        id: ossar

      - name: Upload OSSAR results
        uses: percona-platform/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
